name: Clone repository
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Java setup
        uses: actions/setup-java@v5
        with:
          java-version: 25
      - name: Build
        run: ./gradlew check