name: CI
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Java setup
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
      - name: Build
        run: ./gradlew clean build
      - name: Generate coverage report
        run: ./gradlew jacocoTestReport
      - name: Upload coverage report to codecov.io
        uses: codecov/codecov-action@v4